### ISSUE TITLE
Use !default

### ISSUE THREAD

**Issue by Merovex** [thoughtbot/bitters#300] opened 2018-02-04 16:53 UTC
Just as a suggestion, where you're setting variables consider using !default, which allows me to set that variable up-front. It's only slightly more polite...

**Comment by tysongach** [comment] 2018-02-04 17:50
This is a duplicate of https://github.com/thoughtbot/bitters/issues/195.

Bitters is not a library, but a scaffold of styles (a starting off point) and we encourage you to modify and extend it to meet your design and brand requirements, not override it.

**Closed by tysongach** 2018-02-04 17:50 UTC
