### ISSUE TITLE
Defining Bitters variables as !default

### ISSUE THREAD

**Issue by atcen** [thoughtbot/bitters#276] opened 2017-02-07 09:31 UTC
Example: 
```
// Typography
$base-font-family: $font-stack-system !default;
$heading-font-family: $base-font-family !default;
```

Whit this it would be possible to override variables before including bitters. So bitters will compile with the predefined fonts, etc.

**Comment by tysongach** [comment] 2017-02-07 13:26
This is a duplicate of https://github.com/thoughtbot/bitters/issues/195.

Bitters is not a library, but a scaffold of styles (a starting off point) and we encourage you to modify and extend it to meet your design and brand requirements, not override it.

**Closed by tysongach** 2017-02-07 13:26 UTC
